---
 - hosts: all
   become: true

   tasks:
   - name: all update
     yum:
       name: '*'
       state: latest

   - name: Install the latest version of apache
     yum:
       name: httpd
       state: latest

   - name: Start service httpd and enabled
     service:
       name: httpd
       state: started
       enabled: true